- name: Run Bot
        env:
          USER: ${{ secrets.GOLF_USER }}
          PASS: ${{ secrets.GOLF_PASS }}
          TARGET_TIME: ${{ github.event.inputs.tee_time }}
        run: python bot.py

      - name: Upload Screenshot on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error_screenshot
          path: error_screenshot.png
